name: Meu segundo workflow

on:
  push:
    branches:
    - main

jobs:
  giropops:
      runs-on: ubuntu-latest
      steps:
        - name: Confere versao do ubuntu
          run: cat /etc/os-release
          
        - name: Printa uma mensagem na tela
          run: echo "Meu segundo workflow" > mensagem.txt
        
        - name: Qualqueer outra coisa
          run:  ls -lha
        
        - name: Le conteudo do arquivo
          run: cat mensagem.txt

