name: build e teste
on:
  workflow_call:
    inputs:
      ambiente:
        required: true
        type: string
jobs:
  job-build-e-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Buildando e testando  o ambiente"
        run: echo "make && test ${{inputs.ambiente}}"

  
