name: Deploy the code

on:
  workflow_run:
    workflows: ["build e teste"]
    types:
      - completed

jobs:
  job-publicacao:
    runs-on: ubuntu-latest
    steps:
      - name: "Publica codigo"
        run: echo "Deploying the code"

