name: Deploy the code

on:
  workflow_run:
    workflows: [build e teste]
    types:
      - completed

jobs:
  job-publicacao:
    runs-on: ubuntu-latest
    if: ${{ github.events.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Publica codigo"
        run: echo "Deploying the code"

