name: Chama workflow compartilhado


on:
  workflow_dispatch:
    input:
      nome-do-curso-enviado:
        required: true
        type: string

jobs:
  chama-workflow:
    uses: .github/workflows/trigger-workflow-call.yml
    with:
      nome-do-curso: ${{inputs.node-do-curso-enviado}}
      
