name: Desafio 1
on:
    workflow_dispatch:
        inputs:
            dockerImage:
                description: "Docker Image"
                required: true
                type: string
jobs:
    Desafio-1:
        runs-on: ubuntu-latest
        steps:
            - name: docker pull image
              run: docker pull ${{inputs.dockerImage}}
            - name: list mages
              run: docker images
            - name: inspect the image ${{inputs.dockerImage}}
              run: docker inspect ${{inputs.dockerImage}}
            - name: Docker Scout
              uses: docker/scout-action@v1
              with:
                  command: quickview
                  image: ${{inputs.dockerImage}}
                  write-comment: true
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
