name: Primeiro Workflow Linuxtips

on:
  workflow_dispatch

jobs:
    giropops:
        runs-on: ubuntu-latest
        steps:
            - name: Confere versao do ubuntu 
              run: cat /etc/os-release
            
            - name: Exibir uma mensagem
              run: echo "Estou fazendo o curso de GitHub Actions da Linuxtips"


