name: Pega contexto

on: 
  push

jobs:
  job-pega-contexto:
    runs-on: ubuntu-latest
    steps:
      - name:  Imprime contexto
        env:
          GITHUB_CONTEXTO : ${{toJson(github}}
        run : echo "$GITHUB_CONTEXTO"

