name: Vendo arquivo compartilhado entre Jobs
on:
  push:
    branches:
      - main

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Confere versao do ubuntu 
              run: cat /etc/os-release
            
            - name: Exibir uma mensagem
              run: echo "Estou fazendo o curso de GitHub Actions da Linuxtips" > mensagem.txt
    job_2: 
        runs-on: ubuntu-latest
        steps:
          - name: Acessa arquivo mensagem
            run: ls -lhat mensagem.txt 

          - name: Acessa arquivo mensagem
            run: cat mensagem.txt 

          



