name: Workflow Compartilhado
on: 
  workflow_call:
    inputs:
      nome-do-curso: 
        required: true
        type: string
 jobs:
  fala-o-nome-do-curso:
    runs-on: ubuntu-latest
    steps:
      - name: Informa o nome do curso
        run: O nome do seu curso e ${{inputs.nome-do-curso}}
