name: criando nossa trigger pull-request
on:
  pull_request:
    types: [opened,edited,deleted,reopened]
    branches:
      - "main*"  

jobs:
  job-pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Printa pr
        run: echo "Esse job foi triggado por uma PR com destino a branch main"
