name: criando nossa trigger push
on:
  push:
    branches:
      - "main"
      - "stage"
    paths:
      - "**.tf" 



jobs:
  job-push:
    runs-on: ubuntu-latest
    steps:
      - name: Printa Push
        run: echo "Esse job foi triggado por um push nos branchs main e stage somente com arquivos com extensao .tf"
