name: Testando a regra de delete
on:
  delete:
    
jobs:
  print-modification:
    runs-on: ubuntu-latest
    steps:

        - name: Aviso sobre delecao de branch ou tag
          run: echo "Este workflow foi triagado por uma regra de delete, uma nova branch ou tag foi deletada no repositorio"

