name: Validacao de Ambiente
on:
  workflow_dispatch:

jobs:
  valida-ambiente-prd:
    if: github.ref_name == "main"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Printa valor
        run: echo estou no ambiente ${{ vars.AMBIENTE }}
    
  valida-ambiente-stg:
    if: github.ref_name == "stage"
    runs-ons: ubuntu-latest
    environment: stage
    steps:
      - name: Printa valor
        run: Echo estou no ambiente ${{ vars.AMBIENTE }}

     
    
