name: Validacao de Ambiente
on:
  workflow_dispatch:

env:
  NOME-DO-CURSO: GITHUB Actions
jobs:
  valida-ambiente-prd:
    env:
      DIA-DA-SEMANA: Sexta-feira
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      env:
        DIA-DO-MES: 20 
      - name: Printa valor
        run: echo estou no ambiente ${{ vars.AMBIENTE }} no curso ${{NOME-DO-CURSO}} e hoje e $${DIA-DA-SEMANA}} dia do mes ${{DIA-DO-MES}}
    
  valida-ambiente-stg:
    env:
      DIA-DA-SEMANA: Sabado
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      env:
        DIA-DO-MES: 10
      - name: Printa valor
        run: echo estou no ambiente ${{ vars.AMBIENTE }} no curso ${{NOME-DO-CURSO}} e hoje e dia ${{DIA-DA-SEMANA}} dia do mes ${{DIA-DO-MES}}

     
    
